name: Template API Note Writer

on:
  # Manual trigger: Actions ▸ “Run workflow”
  workflow_dispatch:

  # Automated schedule (uncomment to enable — here, every 30 min)
  #schedule:
  #  - cron: '*/30 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false   # let each run finish even if another starts

jobs:
  regular_run:
    runs-on: ubuntu-latest
    steps:
      # ───────────────────────────────────────────────
      # 1. Check out your fork
      # ───────────────────────────────────────────────
      - name: Check out repository
        uses: actions/checkout@v4

      # ───────────────────────────────────────────────
      # 2. Set up Python 3.12 (default on ubuntu‑latest)
      #    Pin here if you later lock to a different version.
      # ───────────────────────────────────────────────
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ───────────────────────────────────────────────
      # 3. Install uv (fast dependency manager / lockfile tool)
      # ───────────────────────────────────────────────
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # ───────────────────────────────────────────────
      # 4. Create virtualenv & install deps
      #    No --locked → uv refreshes env even if uv.lock is stale.
      #    (Commit a new uv.lock later for fully reproducible builds.)
      # ───────────────────────────────────────────────
      - name: Install project dependencies
        run: cd template-api-note-writer && uv sync

      # ───────────────────────────────────────────────
      # 5. Install xurl CLI (Twitter/X helper)
      # ───────────────────────────────────────────────
      - name: Install xurl CLI
        run: |
          sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/xdevplatform/xurl/main/install.sh)"

      # ───────────────────────────────────────────────
      # 6. Authenticate xurl with your OAuth 1.0 creds
      # ───────────────────────────────────────────────
      - name: Authenticate xurl
        run: |
          xurl auth oauth1 \
            --consumer-key      "$X_API_KEY" \
            --consumer-secret   "$X_API_KEY_SECRET" \
            --access-token      "$X_ACCESS_TOKEN" \
            --token-secret      "$X_ACCESS_TOKEN_SECRET"
        env:
          X_API_KEY:              ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET:       ${{ secrets.X_API_KEY_SECRET }}
          X_ACCESS_TOKEN:         ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET:  ${{ secrets.X_ACCESS_TOKEN_SECRET }}

      # ───────────────────────────────────────────────
      # 7. Run the bot (test_mode default = ON inside main.py)
      #    Set TEST_MODE=0 after the bot is admitted.
      # ───────────────────────────────────────────────
      - name: Run AI Note Writer bot
        run: cd template-api-note-writer && uv run src/main.py
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
